### ISSUE TITLE
self.inventory.getRasters() is an empty list

### ISSUE THREAD

**Issue by zach-cat** [cat-miti/gcbm_preprocessing#10]
After getting issue #9 I made the directory myself and now I get this error

![empty_list](https://user-images.githubusercontent.com/30838944/29082090-5c384732-7c19-11e7-8db7-c321f9d85a86.PNG)

I commented out all the gridding stuff because that seemed to run without an issue over the weekend, but maybe I need to uncomment that stuff?

**Comment by naddison1** [comment]
Keep the updateInv.updateInvRollback() line
