### ISSUE TITLE
CELL_ID needs to be included for all records in the rollback.shp output

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#16]
![image](https://user-images.githubusercontent.com/7143833/29140672-258d3b7e-7d00-11e7-8596-7446631ce517.png)

**Comment by naddison1** [comment]
Yep, I think I know why this is happening

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/545f748760b34807be994664b8875f7fcfd4bc2d
