### ISSUE TITLE
prepFieldMap error: outputField is not supported

### ISSUE THREAD

**Issue by cat-miti** [cat-miti/gcbm_preprocessing#18]
error found for Invermere (tsa 9)

preprocessor.py line 211 mergeDist.runMerDisturbances()

NameError:  the attribute 'outputField' is not supported on this instance of FieldMap

**Comment by B-Ron12** [comment]
similar field map error

![image](https://user-images.githubusercontent.com/7143833/29193498-6d4d8362-7dda-11e7-8bb2-f2ba774a3e1e.png)
