### ISSUE TITLE
Add in projected disturbances script post-rollback in preprocessor

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#24]
M:\Spatially_explicit\01_Projects\17_BC_ON_1ha\03_tools\disturbance_placeholder\00_generate_future_disturbances.py

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/bc4394924a6002b913010f5d05235f51835746d2
