### ISSUE TITLE
reduce number of calculateField occurrences in create_grid.py

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#26]
Make CELL_ID equal to OBJECT_ID

make edits below if time permits but comment out for future runs.

merge calculateField scripts on line 109/110
remove calculateField script on line 112 and have cell ID concatenate from TEST_E field instead.
Do same for Northing (Y) fields

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/612831aacee3d3e950e49466ac94ae529a54690f
