### ISSUE TITLE
Tiler didn't create a directory for my scenarios

### ISSUE THREAD

**Issue by zach-cat** [cat-miti/gcbm_preprocessing#31]
All my runs crashed on tiler.py line 261 because they couldn't find SCEN_BASE folder. I am going to try a local change and run again, I'll check it quickly tomorrow and see if it fixes it.

https://github.com/cat-miti/gcbm_preprocessing/blob/bc390061acda3b3c56ec8799b87d03b65f1f5fe4/03_tiler/tiler.py#L257-L261

I think the logic here works only if there was a previous run done, but not on a fresh run

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/9391ea51cd3be5d97b5c57033765d0e0755db153
