### ISSUE TITLE
Add PercSBofCC variable in update_inventory.py

### ISSUE THREAD

**Issue by benhudson85** [cat-miti/gcbm_preprocessing#33]
Please update the "PercSBofCC = 50" (below) to instead take up the sb_percent variable set in data_prep.py.  This way the rollback and projected slash burn will have the same proportions. Thanks!

def makeSlashburn(self):
        year_range = range(self.rollback_range[0], self.rollback_range[1]+1)
        pp = self.ProgressPrinter.newProcess(inspect.stack()[0][3], len(year_range), 1).start()
        # print "Start of slashburn processing..."
        arcpy.CheckOutExtension("GeoStats")
        PercSBofCC = 50

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/c8666209ce5cde9104c3b98b5086b62c7bf84073
