### ISSUE TITLE
Create SK branch, with the anticipation of a NB, AB, and MB branch in the near future

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#34]
These should use the C2C product for wildfire and harvest by default

**Comment by B-Ron12** [comment]
Did we come up with a plan of attack for this @naddison1 ? Different branch per province or inventory ? or is there a better method of having multiple versions of the preprocessor for different regions of the country? @mfellows

**Comment by mfellows** [comment]
Not sure how much in the repo is generic and how much is region-specific, but you might consider these steps:

- make gcbm_preprocessing the repository for the truly generic code only
- create a new standalone regional_preprocessing repository to hold your region-specific code - you can use branches for each province or whatever in here
- add gcbm_preprocessing as a submodule dependency of regional_preprocessing (see https://github.com/sebastiandev/zipper for an example - note how minizip is a submodule dependency of zipper)
- cloning regional_preprocessing with the --recursive option will clone both regional_preprocessing and its gcbm_preprocessing dependency
- now you can centrally maintain your generic code separately from the truly region-specific details

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/c191a0bb710cd332a7e49ab43bde528f7469c7e8
