### ISSUE TITLE
Slashburn percent must be > 0

### ISSUE THREAD

**Issue by benhudson85** [cat-miti/gcbm_preprocessing#36]
tiler_scenarios = {'Base':[sb_percent, sb_percent, 100],'B':[sb_percent, sb_percent, 95],'D':[sb_percent, 0, 100]}

The 0 value slashburn percent after activity start is not accepted at this stage of projected_disturbances_placeholder.py:

def generateSlashburn(self, harvest_areaValue, projected_disturbances, slashburn_percent, actv_slashburn_percent):
...
            	arcpy.SubsetFeatures_ga(in_features=harvest_proj_dist_temp, out_training_feature_class=r"{}\{}".format(self.outLocation,slasburn_proj_dist_temp), out_test_feature_class="", size_of_training_dataset=PercSBofCC, subset_size_units="PERCENTAGE_OF_INPUT")

Tested with non-zero value (5%) and runs without issue. Error message indicates need for value in range >0 to 100.

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/581a42ccc4d25bba9ff910c7b95665a0719d79a3
