### ISSUE TITLE
add CBMAgeIndicators module to GCBM config template

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#37]
allows for age_class to be a reporting classifier (good to have in disturbance_indicators but can multiply the number of records and size of a db)

       "CBMAgeIndicators": {
            "enabled": true,
            "library": "moja.modules.cbm",
            "order": 15
        },

**Comment by B-Ron12** [comment]
the "order" parameter may vary by what is wanted out of the ageIndicator... In my case I want the stand age at disturbance. This means the order has to come before the disturbance module. If others want to have the age after its grown and decayed then the order will be last

**Comment by naddison1** [comment]
So it should be one before CBMDisturbanceEventModule?
`"Modules": {
        "CBMBuildLandUnitModule": {
            "library": "moja.modules.cbm",
            "order": 1
        },
        "CBMSequencer": {
            "library": "moja.modules.cbm",
            "order": 2
        },
        "CBMAgeIndicators": {
            "enabled": true,
            "library": "moja.modules.cbm",
            "order": 3
        },
        "CBMDisturbanceEventModule": {
            "library": "moja.modules.cbm",
            "order": 4,
            "settings": {
                "vars": "$disturbance_vars"
            },
            "enabled": true
        },
...
`

**Comment by mfellows** [comment]
This issue is a bit outdated with the latest build, sorry Nick - the behaviour of the age class module is less order-dependent now (a good thing): now it only needs to go before CBMAggregatorLandUnitData, and the order shouldn't be user-configurable anymore.

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/855646bb7f496617bb81df3dfe8d24f6a7c3d189
