### ISSUE TITLE
GCBM configs should be parameterized for Master Batch

### ISSUE THREAD

**Issue by naddison1** [cat-miti/gcbm_preprocessing#40]
It seems that master batch will likely always succeed the preprocessor so that configs can be parameterized with that assumption, allowing more flexibility in master batch configurations

**Comment by B-Ron12** [comment]
I think the hope was to not always have to run preprocessor, right? so once the preprocessor run is satisfactory, master batch could be run multiple times from that

**Comment by naddison1** [comment]
Yeah. This will make that better because more of the settings will be set in the master batch opposed to the preprocessor. However the drawback of this is that it makes it hard to run GCBM after the preprocessor without master batch

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/b44b0dce494ba980f84add15f2ea315691add086
