### ISSUE TITLE
SCEN_BASE_GCBM_config_provider.json path issue

### ISSUE THREAD

**Issue by benhudson85** [cat-miti/gcbm_preprocessing#42]
Something that was changed in one of the recent repository commits is impacting the path sent to SCEN_BASE_GCBM_config_provider.json and possibly other configs. It's coming through as this:

"layer_path": "G:\\GCBM\\17_BC_ON_1ha\\05_working_BC_1km\\TSA_10_Kalum\\SCEN_Base\\rollback_fire_1990_moja",

and appears to be missing the 01b_tiled_layers directory like this older one:

"layer_path": "G:\\GCBM\\17_BC_ON_1ha\\05_working_BC\\TSA_23_100_Mile_House\\01b_tiled_layers\\SCEN_Base\\rollback_fire_1990_moja",

**Comment by naddison1** [comment]
In your configuration.xls is the parameter 'GCBM Data Directory' = .\01b_tiled_layers?

**Comment by benhudson85** [comment]
default is set to     .

GCBM Data Directory | .

and by default I just mean the initial value in the excel template. Actual "Default" value is something else entirely.

**Comment by naddison1** [comment]
Try it with .\01b_tiled_layers. I think the newest version of the master batch has this as the new default

**Comment by benhudson85** [comment]
nice! indeed it does. I'm sure that'll take care of the issue. Thanks!
