### ISSUE TITLE
05_hwp_rollup.ini refers to incorrect databases

### ISSUE THREAD

**Issue by benhudson85** [cat-miti/gcbm_preprocessing#44]
Potentially incorrect host/user references. Still seems to run but shouldn't it look to localhost and generic postgres user?

miti_pg_host   = 132.156.148.196
miti_pg_db     = hwp
miti_pg_user   = cat_hwp
miti_pg_pwd    = $1welcome
miti_pg_schema = $schema

...\07_hwp\batch_scripts\05_hwp_rollup.ini

Confirmed values are used in QueryRunner log, e.g. 2017-10-12 11:09:31,464 - hwp:TSA_10_Kalum_Base_Base@132.156.148.196

**Comment by naddison1** [comment]
It points to the HWP postgres server. We could change it to local instead if that's preferred

**Comment by benhudson85** [comment]
I've updated the 05_hwp_rollup.ini at this location: M:\Spatially_explicit\01_Projects\17_BC_ON_1ha\03_tools\Master_Batch_Templates\07_hwp\batch_scripts

The default settings are now for localhost, etc.  This change will eventually need to make it to the new master batch repository that we've just started using.
