### ISSUE TITLE
shape file lock

### ISSUE THREAD

**Issue by cat-miti** [cat-miti/gcbm_preprocessing#7]
Still hitting lock error associated with:    for spatial_input in copy:
        spatial_input.copy(spatial_input.getWorkspace().replace(clipped_redirection[0], clipped_redirection[1]))
for TSA shapefile

**Comment by naddison1** [comment]
I believe the update https://github.com/cat-miti/gcbm_preprocessing/commit/156816b83ace3e32db8de3d418ae93e61ea7c424 solved this. Let me know if you have this updated version and you're still getting the problem
