### ISSUE TITLE
Fail on exportGriddedInvDBF

### ISSUE THREAD

**Issue by B-Ron12** [cat-miti/gcbm_preprocessing#8]
failed to convert .\00_Workspace.gdb\inventory_gridded. ERROR 99999. Error executing function.
The field is not nullable [TEST_E2]
....
Failed to executre (CopyRows)

**Comment by zach-cat** [comment]
![not_nullable](https://user-images.githubusercontent.com/30838944/29082422-4a02e620-7c1a-11e7-979d-e36ffbd15738.PNG)


I got the same on my run as well.

**Comment by naddison1** [comment]
Looking like another memory issue. I will change it so that it only exports the necessary fields for woodstock

**Comment by naddison1** [comment]
https://github.com/cat-miti/gcbm_preprocessing/commit/55c33829d91d5910e3c81dc256f97600964e55c1
