### ISSUE TITLE
Tiler output directory not created by data_prep.py

### ISSUE THREAD

**Issue by zach-cat** [cat-miti/gcbm_preprocessing#9]
When I ran prince george, this directory was created for me, but it was not created for robson valley or quesnal. 
![error](https://user-images.githubusercontent.com/30838944/29081768-46a2824e-7c18-11e7-9d45-daf21d529a7e.PNG)
This is how the relevant line looks in my data_prep.py.
![dir](https://user-images.githubusercontent.com/30838944/29081868-a8e1ec24-7c18-11e7-8eb7-cb3231b0bea5.PNG)

**Comment by naddison1** [comment]
In the future, the tiler_output_dir should just be r"{}\01b_tiled_layers". The bounding box will be created in that main directory, then it will create the scenario specific directory, SCEN_TEST, or Base
